### PR TITLE
Add typescript types

### PR DESCRIPTION
**Pull request by mindsers**
This PR:
- adds the typescript types from `DefinitelyTyped`.
- changes the `Dayzed` component type to be a function component and not a class component
- adds a npm script to test if the types are still valid (if typescript can build a react code using the Dayzed's types)

Related to #36

### CODE REVIEW

**Comment by mkartchner994** [comment]
@mindsers Thanks for doing this! I think this looks great. I would like to take a little extra time to go over this PR as I don't really know typescript well and I think this will give me a good opportunity to dig in and learn from what you have done. I'll let you know if any questions come up. Thanks again 👍

**Comment by mindsers** [comment]
No problem. Take your time and let me know when you need me! 😉

**Comment by mkartchner994** [comment]
@mindsers I finally took some time to dig into TypeScript this weekend and think I was able to get my bearings straight. I really appreciate you adding the `typings/dayzed-tests.tsx` and the `test:types` script as that helped me work with the types much easier in the project. Here are some things I would love to get your feedback on:

- I noticed the `dayzed-tests.tsx` file is only using `{calendars, getDateProps}` from the child render function and custom hook, but I think it might make sense to also bring in `{getBackProps, getForwardProps}` for testing as well?

- This also lead me to look at the types for the getter props (Date, Back, Forward) a little closer and I think it might make sense to update those to extend from `React.HTMLProps<HTMLButtonElement>` because if you try to pass something that should be for the element (onClick, style, className, etc) TypeScript shows this as an error.
image

- Lastly, I think the `@types/react-dom` and `typescript` packages should maybe move into the `devDependencies`. I read through the [TypeScript Publish](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) doc but, truthfully, it confused me a little. I looked at a few other libraries (one being [Downshift](https://github.com/downshift-js/downshift/blob/master/package.json#L87) which this is heavily inspired by) and it seems like many JS libraries have them in `devDependencies`

Since I was diving into it this weekend I have this work done locally. If we feel good about these changes I can push that up as a commit to this PR - or if you wanted to update them, whatever you prefer I am good with. Let me know your thoughts on the above ideas. Thanks!

**Comment by mindsers** [comment]
@mkartchner994 I agree with all these feedbacks. 

The two first feedbacks are the arguments that justify the need of having the types directly in this repo. To be honest the types were mostly a copy/paste from `DefinitelyTyped` except for the main function component (`Dayzed`). Having the types here with those changes (function component + your feedbacks) will be a real improvement for typescript users of Dayzed. 

Not having `typescript` and `@types/...` packages in `devDependencies` is a mistake. Since the browser doesn't know typescript those packages are completely useless in production and are used only at build time. I think my `npm install` arguments were bad 😕 

Since you already did the work, I think you should push it to this PR. 👌🏽 Thanks for your feedbacks!

**Comment by mkartchner994** [comment]
@mindsers Those are pushed up. I also added you to the Contributors list 💪  (hope that is alright). 

I don't know what the SemVer update should be for this release. If someone has `@types/dayzed` installed but then updates to this version of Dayzed would that cause issues? Also, I don't know if because we are exporting two new interfaces - `GetBackForwardPropsOptions` and `GetDatePropsOptions` - if this would cause a breaking change? I'm guessing it probably wouldn't, but being new to TypeScript I'm not sure. My thought is I would just bump it up to the next minor version - 3.2.0. 

Let me know what you think. Thanks!

**Comment by mindsers** [comment]
@mkartchner994 Hi! Thanks for adding me to the list.

I think it should be a minor version because it adds a new feature (the types) and it shouldn't add breaking changes. I just tried this PR in an existing project using the `@types/dayzed` and my tools (editor + compiler) automatically used the new types from the dayzed repo even if the @types/dayzed are still installed.

**Comment by mkartchner994** [comment]
This has been released as `3.2.0`. Thanks @mindsers!

**Pull request merged**
